# ---------------------------------------------------------------------------
# Woodpecker CI — VoteChain Build/Test + Pages Deploy
# ---------------------------------------------------------------------------
# Runs tests/typecheck/build on push, pull request, and manual runs.
# Deploys to votechain-test on push/manual to main.
# Optional production deploy is manual-only.
# ---------------------------------------------------------------------------

when:
  - event: [push, pull_request, manual]

steps:
  - name: install
    image: node:22-alpine
    commands:
      - npm ci

  - name: test
    image: node:22-alpine
    commands:
      - npm test

  - name: typecheck
    image: node:22-alpine
    commands:
      - npm run typecheck

  - name: build
    image: node:22-alpine
    commands:
      - npm run build

  - name: deploy-test
    image: node:22-alpine
    commands:
      - npm run deploy:test
    depends_on:
      - build
    when:
      - event: [push, manual]
        branch: main
    environment:
      CLOUDFLARE_API_TOKEN:
        from_secret: cloudflare_api_token
      CLOUDFLARE_ACCOUNT_ID:
        from_secret: cloudflare_account_id

  - name: deploy-production
    image: node:22-alpine
    commands:
      - npm run deploy:prod
    depends_on:
      - deploy-test
    when:
      - event: [manual]
        branch: main
    environment:
      CLOUDFLARE_API_TOKEN:
        from_secret: cloudflare_api_token
      CLOUDFLARE_ACCOUNT_ID:
        from_secret: cloudflare_account_id
